name: flutter_navigation_app
description: "FLutter Navigation App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/doggo.JPG



  
